name: cpp17:clang9:ubuntu

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        build_mode: ["Release", "Debug"]
        panic_backtrace: ["ON", "OFF"]
        backtrace: ["ON", "OFF"]

    steps:
      - uses: actions/checkout@v2

      - name: Install GoogleTest
        run: git clone https://github.com/google/googletest.git && cd googletest && mkdir build && cd build && cmake ..   && sudo make install


      - name: Install Abseil
        run: git clone https://github.com/abseil/abseil-cpp.git && cd abseil-cpp && mkdir build && cd build && cmake ..   && sudo make install


      - name: Install Clang-9
        run: sudo apt install clang-9

      - name: Configure Build Directory
        run: mkdir build

      - name: Initialize CMake
        run: cd build && export CC=clang-9 CXX=clang++-9 && cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_mode }} -DSTX_BUILD_TESTS=ON -DSTX_ENABLE_BACKTRACE=${{ matrix.backtrace }} -DSTX_ENABLE_PANIC_BACKTRACE=${{ matrix.panic_backtrace }} -DSTX_SANITIZE_TESTS=ON

      - name: Run Unsanitized Tests
        run: cd build && make stx_span_tests stx_option_result_tests && ./span/stx_span_tests && ./option_result/option_result_tests

      #- name: Run Address-sanitized Tests
      #  run: cd build && make stx_tests_address_sanitized && ./stx_tests_address_sanitized

      #- name: Run Leak-sanitized Tests
      #  run: cd build && make stx_tests_leak_sanitized && ./stx_tests_leak_sanitized

      #- name: Run Thread-sanitized Tests
      #  run: cd build && make stx_tests_thread_sanitized && ./stx_tests_thread_sanitized

      #- name: Run Undefined-sanitized Tests
      #  run: cd build && make stx_tests_undefined_sanitized && ./stx_tests_undefined_sanitized
